### ISSUE TITLE
Migrate DB from PlanetScale to Neon (or other alternative)

### ISSUE THREAD

**Issue by ross-brown** [ross-brown/ecommerce-dashboard#1]
PlanetScale hobby plan is expiring on April 8th. Only I can do this since it's under my account and I control the DB.

**Comment by ross-brown** [comment]
Remembered that the DB used for this is MySQL and NOT PostgreSQL. So I migrated the database from PlanetScale to Aiven.

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.
